
/* Create a new SQL Server database to contain replicated tables */

USE [master]
GO

CREATE DATABASE [SqlReplication]
 CONTAINMENT = NONE
 ON  PRIMARY ( NAME = N'SqlReplicationIoHooks', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\SqlReplication.mdf' , SIZE = 10MB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON ( NAME = N'SqlReplicationIoHooks_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\SqlReplication_log.ldf' , SIZE = 5MB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [SqlReplication] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SqlReplication].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SqlReplication] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SqlReplication] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SqlReplication] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SqlReplication] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SqlReplication] SET ARITHABORT OFF 
GO

ALTER DATABASE [SqlReplication] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SqlReplication] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SqlReplication] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SqlReplication] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SqlReplication] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SqlReplication] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SqlReplication] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SqlReplication] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SqlReplication] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SqlReplication] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SqlReplication] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SqlReplication] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SqlReplication] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SqlReplication] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SqlReplication] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SqlReplication] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SqlReplication] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SqlReplication] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SqlReplication] SET  MULTI_USER 
GO

ALTER DATABASE [SqlReplication] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SqlReplication] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SqlReplication] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SqlReplication] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SqlReplication] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SqlReplication] SET QUERY_STORE = OFF
GO

USE [SqlReplication]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [SqlReplication] SET  READ_WRITE 
GO

/* Create a new SQL Server login for the replicator to use */

USE [master]
GO

CREATE LOGIN [SqlReplicationUser] WITH PASSWORD='SqlReplicationPassword', DEFAULT_DATABASE=[SqlReplication], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

/* Allow the new user to perform bulk operations */

GRANT ADMINISTER BULK OPERATIONS TO [SqlReplicationUser]
GO

/* Change the database owner to the new login */

USE [SqlReplication]
GO

EXEC sp_changedbowner [SqlReplicationUser]; 
GO


USE [master]
GO
